'use client';

import React from 'react';
import { Navbar } from '@/components/Navbar';
import { Footer } from '@/components/Footer';
import { ShieldCheck, HelpCircle, Coins, Users, Lock } from 'lucide-react';

export default function FAQ() {
  const faqs = [
    {
      category: "General",
      icon: HelpCircle,
      items: [
        {
          q: "What is StakePot?",
          a: "StakePot is a no-loss prize protocol built on the Casper Network. It allows you to deposit CSPR for a chance to win weekly jackpots without ever losing your initial deposit."
        },
        {
          q: "How is it 'No-Loss'?",
          a: "Your deposit is never used for the prize. Instead, all deposits are pooled together and staked. The staking rewards (yield) generated by the pool form the prize. Even if you don't win, you can withdraw your full deposit back."
        }
      ]
    },
    {
      category: "Prizes & Winning",
      icon: Coins,
      items: [
        {
          q: "How are winners chosen?",
          a: "Winners are selected using a Verifiable Random Function (VRF) on-chain. This ensures the process is provably fair and cannot be manipulated by anyone, including the developers."
        },
        {
          q: "What are my chances of winning?",
          a: "Your chances are proportional to your deposit size. If you contribute 1% of the total pool, you have a 1% chance of winning. Joining a Squad can also earn you bonus rewards even if you don't win the main jackpot."
        }
      ]
    },
    {
      category: "Security & Funds",
      icon: ShieldCheck,
      items: [
        {
          q: "Is my money safe?",
          a: "Yes. Your funds are deposited into a smart contract that delegates them to reputable Casper validators. The protocol has been audited to ensure there are no backdoors."
        },
        {
          q: "Can I withdraw anytime?",
          a: "You can request a withdrawal at any time. However, due to Casper Network's staking mechanism, there is a standard unbonding period (usually ~7 eras or ~14 hours) before funds are returned to your wallet."
        }
      ]
    }
  ];

  return (
    <div className="min-h-screen bg-cream text-dark font-sans selection:bg-gold selection:text-white">
      <Navbar />
      
      <main className="pt-32 pb-20 px-4">
        <div className="max-w-4xl mx-auto">
          
          <div className="text-center mb-16">
            <h1 className="text-4xl md:text-5xl font-bold mb-6 font-display">Frequently Asked Questions</h1>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Everything you need to know about the protocol, security, and winning mechanisms.
            </p>
          </div>

          <div className="space-y-12">
            {faqs.map((section, idx) => (
              <div key={idx} className="glass-card p-8">
                <div className="flex items-center gap-3 mb-8 border-b border-gray-200 pb-4">
                  <section.icon className="w-6 h-6 text-orange" />
                  <h2 className="text-2xl font-bold text-dark">{section.category}</h2>
                </div>
                
                <div className="grid gap-8">
                  {section.items.map((item, i) => (
                    <div key={i}>
                      <h3 className="font-bold text-lg mb-2 text-dark">{item.q}</h3>
                      <p className="text-gray-600 leading-relaxed">{item.a}</p>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>

          <div className="mt-12 text-center p-8 bg-dark rounded-3xl text-white">
            <h3 className="text-2xl font-bold mb-4">Still have questions?</h3>
            <p className="text-gray-400 mb-6">Join our community on Discord or Telegram to chat with the team.</p>
            <div className="flex justify-center gap-4">
              <button className="px-6 py-3 bg-white/10 hover:bg-white/20 rounded-full font-bold transition">
                Join Discord
              </button>
              <button className="px-6 py-3 bg-gold text-dark hover:bg-orange hover:text-white rounded-full font-bold transition">
                Telegram Group
              </button>
            </div>
          </div>

        </div>
      </main>

      <Footer />
    </div>
  );
}
